language: cpp
os: linux
dist: bionic

before_install:
  - sudo apt-get install qt5-default libboost-all-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  # - make test
  - cd ..
  - ./scripts/lint.sh
  - ./scripts/check_format.sh || { echo -e "\nCode not correctly formated!" && exit 1; }
