language: cpp
os: linux
dist: bionic

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - qt5-default
      - libboost-all-dev

before_install:
  - echo $LANG
  - echo $LC_ALL

before_script:
  - ./scripts/setup_build.sh

script:
  - ./scripts/build.sh
  - ./scripts/test.sh

jobs:
  include:
    - name: Linting
      script: ./scripts/lint.sh
      allow_failure: true
    - name: Check code format
      script: ./scripts/check_format.sh
      allow_failure: true
